/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */

#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct {
    const char *p;
    ptrdiff_t n;
} _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */

#line 3 "gtruntime.go"

#include "../gtruntime.h"
#include <stdint.h>
#include <stdlib.h>

typedef void (*c_void_func_t)(void *);
typedef void *(*c_ptr_func_t)(void *);
typedef int (*c_int_func_t)(void *);

// Trampolines to invoke C function pointers from Go
static inline void invoke_void_func(c_void_func_t fn, void *arg) { fn(arg); }

static inline void *invoke_ptr_func(c_ptr_func_t fn, void *arg) {
    return fn(arg);
}

static inline int invoke_int_func(c_int_func_t fn, void *arg) {
    return fn(arg);
}

typedef const void *gt_chan_arg_data;

#line 1 "cgo-generated-wrapper"

/* End of preamble from import "C" comments.  */

/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char
    _check_for_64_bit_pointer_matching_GoInt[sizeof(void *) == 64 / 8 ? 1 : -1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct {
    void *t;
    void *v;
} GoInterface;
typedef struct {
    void *data;
    GoInt len;
    GoInt cap;
} GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void gt_init(void);
extern void gt_shutdown(void);
extern uint64_t gt_spawn_void(c_void_func_t fn, void *arg);
extern uint64_t gt_spawn_ptr(c_ptr_func_t fn, void *arg);
extern uint64_t gt_spawn_int(c_int_func_t fn, void *arg);
extern uint64_t gt_spawn_go_task(uint32_t task_id, void *arg);
extern int gt_join(uint64_t h);
extern int gt_join_ptr(uint64_t h, void **result);
extern int gt_join_int(uint64_t h, int *result);
extern _Bool gt_task_done(uint64_t h);
extern int gt_join_all(void);
extern uint64_t gt_chan_create(uint32_t capacity);
extern void gt_chan_close(uint64_t h);
extern int gt_chan_send(uint64_t h, gt_chan_arg_data data, uint32_t length);
extern int gt_chan_try_send(uint64_t h, gt_chan_arg_data data, uint32_t length);
extern int gt_chan_recv(uint64_t h, void *buf, uint32_t maxlen,
                        uint32_t *out_len);
extern int gt_chan_try_recv(uint64_t h, void *buf, uint32_t maxlen,
                            uint32_t *out_len);
extern uint32_t gt_chan_len(uint64_t h);
extern uint32_t gt_chan_cap(uint64_t h);
extern int gt_select(gt_select_case_t *cases, uint32_t num_cases);
extern uint64_t gt_wg_create(void);
extern void gt_wg_add(uint64_t h, int delta);
extern void gt_wg_done(uint64_t h);
extern void gt_wg_wait(uint64_t h);
extern void gt_wg_destroy(uint64_t h);
extern uint64_t gt_mutex_create(void);
extern void gt_mutex_lock(uint64_t h);
extern void gt_mutex_unlock(uint64_t h);
extern _Bool gt_mutex_try_lock(uint64_t h);
extern void gt_mutex_destroy(uint64_t h);
extern uint64_t gt_ctx_background(void);
extern uint64_t gt_ctx_with_cancel(uint64_t parent);
extern uint64_t gt_ctx_with_timeout(uint64_t parent, uint64_t timeout_ms);
extern uint64_t gt_ctx_with_deadline(uint64_t parent, int64_t deadline_unix_ms);
extern void gt_ctx_cancel(uint64_t h);
extern _Bool gt_ctx_is_done(uint64_t h);
extern uint64_t gt_ctx_done_chan(uint64_t h);
extern void gt_ctx_destroy(uint64_t h);
extern uint64_t gt_timer_after(uint64_t duration_ms);
extern uint64_t gt_timer_create(uint64_t duration_ms);
extern _Bool gt_timer_stop(uint64_t h);
extern _Bool gt_timer_reset(uint64_t h, uint64_t duration_ms);
extern uint64_t gt_timer_chan(uint64_t h);
extern void gt_timer_destroy(uint64_t h);
extern uint64_t gt_ticker_create(uint64_t period_ms);
extern uint64_t gt_ticker_chan(uint64_t h);
extern void gt_ticker_stop(uint64_t h);
extern void gt_ticker_destroy(uint64_t h);
extern void gt_sleep(uint64_t duration_ms);
extern int64_t gt_now_unix_ms(void);
extern uint32_t gt_num_cpu(void);
extern uint32_t gt_num_goroutine(void);
extern void gt_gosched(void);

#ifdef __cplusplus
}
#endif
